### ISSUE TITLE
Z-Wave JS issue after update

### ISSUE THREAD

**Issue by cidux** [hassio-addons/addon-zwave-js-ui#585] opened 2023-09-28 04:53 UTC
# Problem/Motivation
My Devices no longer connect and given issue of Image ghcr.io/hassio-addons/zwave-js-ui/amd64:2.0.1 does not exist for addon_a0d7b954_zwavejs2mqtt

> (Why the issue was filed)

## Expected behavior
Plugin starts up.
> (What you expected to happen)

## Actual behavior
Plugin fails to start.
> (What actually happened)

## Steps to reproduce
Just updated the z-wave js to the one released 8 hours ago.

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by cidux** [comment] 2023-09-28 04:53
![Screenshot_20230928_004951_Home Assistant](https://github.com/hassio-addons/addon-zwave-js-ui/assets/21992886/1d992e8e-ab38-47bf-9e71-d0e16b1e072b)

**Comment by Teonyr** [comment] 2023-09-28 05:38
Same here, after updating, the addon fails to start with following message:

```
Image ghcr.io/hassio-addons/zwave-js-ui/aarch64:2.0.1 does not exist for addon_a0d7b954_zwavejs2mqtt
```

**Comment by jblamotte** [comment] 2023-09-28 07:27
Same issue here => image does not exist. (with hassio ... can't do a docker pull...)

**Comment by toddward** [comment] 2023-09-28 17:20
Also having the same issue.

**Comment by matt-from-uk** [comment] 2023-09-28 18:10
Same. I am pleased it is not just me, but not that nothing in my house is now working.

**Comment by toddward** [comment] 2023-09-28 18:11
@matt-from-uk same issue...nothing in my house is working.

**Comment by cidux** [comment] 2023-09-28 18:13
After I noticed this last night I was messing with it a bit and atleast got my lamps with inovelli bulbs working but none of my other z-wave devices work either.

**Comment by bpbradley** [comment] 2023-09-28 19:22
Same here. I restored the backup with 1.16.0 and it is working again.

**Comment by matt-from-uk** [comment] 2023-09-28 19:39
> Same here. I restored the backup with 1.16.0 and it is working again.

This is the answer. Navigate to backups and restore the one that was automatically taken on the update to go back to 1.16.0. All is back to normal after. 

Time to turn off automatic updates I think.

**Comment by ashwin2101** [comment] 2023-09-28 20:01
Same here, had to restore the backup to 1.16.0

**Comment by bistek22** [comment] 2023-09-28 21:23
**HA v2023.9.3**

In my case, it's not working either after installing version 2.0.1; it keeps displaying an error message constantly. Logs below. I'm using RaZberry2.

`Logger: homeassistant.components.zwave_js
Source: components/zwave_js/entity.py:337
Integration: Z-Wave (documentation, issues)
First occurred: 22:48:13 (1 occurrences)
Last logged: 22:48:13

Unable to set value 2-37-1-targetValue: Z-Wave error 103: The controller is not yet ready! (ZW0103)`

`2023-09-28 22:58:57.270 INFO Z-WAVE: Network scan complete. Found: 13 nodes
2023-09-28 22:58:57.331 INFO Z-WAVE-SERVER: DNS Service Discovery enabled
2023-09-28 22:58:59.302 INFO Z-WAVE: Next update scheduled for: Fri Sep 29 2023 00:00:00 GMT+0200 (Central European Summer Time)
2023-09-28 22:59:09.390 INFO APP: GET /health/zwave 301 1.622 ms - 191
2023-09-28 22:59:39.543 INFO APP: GET /health/zwave 301 1.578 ms - 191
2023-09-28 23:00:04.002 INFO Z-WAVE: Controller status: Controller is unresponsive
2023-09-28 23:00:06.646 INFO Z-WAVE: Controller status: Controller is Ready
2023-09-28 23:00:09.707 INFO APP: GET /health/zwave 301 1.581 ms - 191
2023-09-28 23:00:39.875 INFO APP: GET /health/zwave 301 1.874 ms - 191`

**Comment by adrum** [comment] 2023-09-29 16:26
I was able to resolve this by:

1. Install "Advanced SSH & Web Terminal" Add-On
2. Disable Protection Mode
3. Start/Restart "Advanced SSH & Web Terminal" Add-On
4. Open Add-On Web UI 
5. Run `docker pull ghcr.io/hassio-addons/zwave-js-ui/aarch64:2.0.1` (be sure to note the applicable architecture)
6. Start "Z-Wave JS UI" Add-On
7. Re-enable Protection Mode
8. Stop/Restart "Advanced SSH & Web Terminal" Add-On
9. Restart HomeAssistant or Reload Z-Wave JS integration

**Comment by bistek22** [comment] 2023-09-30 14:12
> I was able to resolve this by:
> 
>     1. Install "Advanced SSH & Web Terminal" Add-On
> 
>     2. Disable Protection Mode
> 
>     3. Start/Restart "Advanced SSH & Web Terminal" Add-On
> 
>     4. Open Add-On Web UI
> 
>     5. Run `docker pull ghcr.io/hassio-addons/zwave-js-ui/aarch64:2.0.1` (be sure to note the applicable architecture)
> 
>     6. Start "Z-Wave JS UI" Add-On
> 
>     7. Optional: Re-enable Protection Mode for "Advanced SSH & Web Terminal" Add-On
> 
>     8. Stop/Restart "Advanced SSH & Web Terminal" Add-On
> 
>     9. Restart HomeAssistant or Reload Z-Wave JS integration

It still doesn't work, I've tried everything already. Does the author of the add-on plan to do something about it?

**Comment by bpbradley** [comment] 2023-09-30 14:14
> > I was able to resolve this by:
> > 
> >     1. Install "Advanced SSH & Web Terminal" Add-On
> > 
> >     2. Disable Protection Mode
> > 
> >     3. Start/Restart "Advanced SSH & Web Terminal" Add-On
> > 
> >     4. Open Add-On Web UI
> > 
> >     5. Run `docker pull ghcr.io/hassio-addons/zwave-js-ui/aarch64:2.0.1` (be sure to note the applicable architecture)
> > 
> >     6. Start "Z-Wave JS UI" Add-On
> > 
> >     7. Optional: Re-enable Protection Mode for "Advanced SSH & Web Terminal" Add-On
> > 
> >     8. Stop/Restart "Advanced SSH & Web Terminal" Add-On
> > 
> >     9. Restart HomeAssistant or Reload Z-Wave JS integration
> 
> It still doesn't work, I've tried everything already. Does the author of the add-on plan to do something about it?

Did you not try restoring from backup? Home assistant makes a backup before updating, you should be able to restore that.

**Comment by vectorxy** [comment] 2023-09-30 17:28
> > > I was able to resolve this by:
> > > ```
> > > 1. Install "Advanced SSH & Web Terminal" Add-On
> > > 
> > > 2. Disable Protection Mode
> > > 
> > > 3. Start/Restart "Advanced SSH & Web Terminal" Add-On
> > > 
> > > 4. Open Add-On Web UI
> > > 
> > > 5. Run `docker pull ghcr.io/hassio-addons/zwave-js-ui/aarch64:2.0.1` (be sure to note the applicable architecture)
> > > 
> > > 6. Start "Z-Wave JS UI" Add-On
> > > 
> > > 7. Optional: Re-enable Protection Mode for "Advanced SSH & Web Terminal" Add-On
> > > 
> > > 8. Stop/Restart "Advanced SSH & Web Terminal" Add-On
> > > 
> > > 9. Restart HomeAssistant or Reload Z-Wave JS integration
> > > ```
> > 
> > 
> > It still doesn't work, I've tried everything already. Does the author of the add-on plan to do something about it?
> 
> Did you not try restoring from backup? Home assistant makes a backup before updating, you should be able to restore that.

I tried restoring in HA the backup that was taken before zwave js ui was updated. I roll back to 1.16.0 and try to startup the addon and it complains that it can't locate 1.16.0 for the GitHub repo. I found the soft-reset fix as I'm running HA as a unraid vm, which is like a KVM vm. I tried unplugging the stick and replugging the HUSBZB-1 stick back in even rebooted the vm. No change zwave devices don't work. I'm at a loss and I might try the ssh steps above when I get a chance. But if someone knows what I'm doing wrong with roll back process I'd appreciate a little point in the right direction.

**Comment by cidux** [comment] 2023-09-30 17:59
I restored from back up and had to delete my z-wave integration and re-add it again in the integrations dashboard but the actual tab had all the info correct so it just re-pulled all the info back in.

**Comment by vectorxy** [comment] 2023-10-01 05:31
> I restored from back up and had to delete my z-wave integration and re-add it again in the integrations dashboard but the actual tab had all the info correct so it just re-pulled all the info back in. I am still running the older version make sure you set your z-stick in the addon tab in HA as mine didn't set correctly and I had to set it again.

Looks like by the grace of God I was able to rollback to 1.16.0 and not sure what I did to get past my previous error. But it looks like things are back to normal for me and this is the only thing that was able to fix my zwave network. Soft reset fix definitely is not working for my issue. I guess I'll wait to the next update apply and see what happens.

**Comment by firefighter4700** [comment] 2023-10-01 22:32
Hi. The "soft reset" did not work for me. I am also out of luck with my backups because of worktravel i did not get a chance to save my earliest backup before they were overwritten. I am defininatly changing my backup polisy to several backups before they get auto deleted and no more auto-update for me.

Anyway; does anyone got a basic instruction, for a newbee, on how to rollback the version on zwave js ui to 1.16.0 or is it possibe to just uninstall the 2.0.1 and install 1.16.0 directly?

**Comment by cidux** [comment] 2023-10-01 23:37
One way would be to uninstall and make sure you download the correct version but you would have to reinterview all your devices which is a work around but just sucks. If you don't have backups tho you probably will have to do that. Are you sure there are none, by default Home Assistant takes them for you. Unless you opted out of it. 
![Screenshot_20231001_193655_Home Assistant](https://github.com/hassio-addons/addon-zwave-js-ui/assets/21992886/b61444ee-b686-48b1-9676-9e5395ca9fa5) in the back ups kn this page it should have them saved automatically again unless you opted out

**Comment by firefighter4700** [comment] 2023-10-01 23:48
> One way would be to uninstall and make sure you download the correct version but you would have to reinterview all your devices which is a work around but just sucks. If you don't have backups tho you probably will have to do that. Are you sure there are none, by default Home Assistant takes them for you. Unless you opted out of it. ![Screenshot_20231001_193655_Home Assistant](https://user-images.githubusercontent.com/21992886/271859404-b61444ee-b686-48b1-9676-9e5395ca9fa5.jpg) in the back ups kn this page it should have them saved automatically again unless you opted out

Yes, as a newbee, I opted out for anything but full backups. This will change :-) I am ok with adding nodes again if nessesary, but I can't see anywhere  it is possible to pick what version to install. Only 2.0.1 shows up... Am I missing something?

**Comment by cidux** [comment] 2023-10-02 03:54
I believe it should give you the option to install older versions. I've had to do it in the past when an update broke my stuff so I had to reinterview everything. It should have a drop down when you go to install to choose the version.

**Comment by firefighter4700** [comment] 2023-10-02 07:54
> I believe it should give you the option to install older versions. I've had to do it in the past when an update broke my stuff so I had to reinterview everything. It should have a drop down when you go to install to choose the version.

Sorry, not as I can see. There is only the install button an then it installs 2.0.1 directly..
Seems very strange that there is not released any update fix for this..

**Comment by bhaggs** [comment] 2023-10-05 16:36
Word of caution, if you need to remain at version 1.16.0 you won't be able to upgrade to Home Assistant 2023.10. I tried loading it last night and it requires the newer version of zwave js server. I just rolled back my instance to 2023.9 so that I can continue to run 1.16.0 of Z-Wave JS UI.

**Comment by cidux** [comment] 2023-10-05 16:49
That is correct, but after I updated my HA core I updated my z-wave and it's working like it should. I also was given another update for z-wave after I updated my HA core. It's all back to working atleast for me.

**Comment by firefighter4700** [comment] 2023-10-05 19:10
Have anyone tried the 2.0.2 version? Are we back to normal with this? Had to uninstall my js ui addon and move all my z wave divices to the js addon. Really want to swich back again..

**Comment by cidux** [comment] 2023-10-05 19:20
> Have anyone tried the 2.0.2 version? Are we back to normal with this? Had to uninstall my js ui addon and move all my z wave divices to the js addon. Really want to swich back again..

As I said in my above it seems to be working again with 2.02. I was having issues with it and it seems to be working again. You could try it and see if it works for you but its working for me.

**Comment by firefighter4700** [comment] 2023-10-05 19:26
> > Have anyone tried the 2.0.2 version? Are we back to normal with this? Had to uninstall my js ui addon and move all my z wave divices to the js addon. Really want to swich back again..
> 
> As I said in my above it seems to be working again with 2.02. I was having issues with it and it seems to be working again. You could try it and see if it works for you but its working for me.

Ok, wasnt sure if you had tested all yet, but good! I will try it out tomorrow and report back. Thaks!

**Comment by cidux** [comment] 2023-10-05 19:30
> > > Have anyone tried the 2.0.2 version? Are we back to normal with this? Had to uninstall my js ui addon and move all my z wave divices to the js addon. Really want to swich back again..
> > 
> > 
> > As I said in my above it seems to be working again with 2.02. I was having issues with it and it seems to be working again. You could try it and see if it works for you but its working for me.
> 
> Ok, wasnt sure if you had tested all yet, but good! I will try it out tomorrow and report back. Thaks!

I have not tested everything yet. But it all seems to be working as it should again. I have not added any devices yet since I updated but it is working in HA and I didn't have to change anything after updating just worked like usual.

**Closed** 2023-10-05 19:31 UTC

**Comment by toddward** [comment] 2023-10-06 01:55
2.0.2 seems to be working quite well.  Thanks for the update!!

**Comment by ashwin2101** [comment] 2023-10-06 10:11
I upgraded zwave js to 2.0.2 and I upgraded the "aeotect stick Gen-5" to the latest firmware but the controler is still crashing every few minutes :(



_______________________________________________________________
2023-10-06T10:08:12.586Z CNTRLR   The controller is unresponsive
2023-10-06 12:08:12.587 INFO Z-WAVE: Controller status: Controller is unresponsive
2023-10-06T10:08:12.588Z DRIVER   Attempting to recover unresponsive controller...
2023-10-06T10:08:12.590Z CNTRLR   Performing soft reset...
2023-10-06T10:08:12.601Z CNTRLR   Waiting for the controller to reconnect...
2023-10-06T10:08:14.102Z CNTRLR   Re-opening serial port...
2023-10-06T10:08:15.106Z CNTRLR   Waiting for the Serial API to start...
2023-10-06T10:08:15.544Z CNTRLR   Serial API started
2023-10-06T10:08:15.545Z CNTRLR   The controller is no longer unresponsive
2023-10-06 12:08:15.546 INFO Z-WAVE: Controller status: Controller is Ready

_______________________________________________________________

![image](https://github.com/hassio-addons/addon-zwave-js-ui/assets/56930394/81a78b15-26dd-428f-b19c-f362f6d49384)

**Comment by ashwin2101** [comment] 2023-10-06 12:36
> I upgraded zwave js to 2.0.2 and I upgraded the "aeotect stick Gen-5" to the latest firmware but the controler is still crashing every few minutes :(
> 
> 2023-10-06T10:08:12.586Z CNTRLR The controller is unresponsive 2023-10-06 12:08:12.587 INFO Z-WAVE: Controller status: Controller is unresponsive 2023-10-06T10:08:12.588Z DRIVER Attempting to recover unresponsive controller... 2023-10-06T10:08:12.590Z CNTRLR Performing soft reset... 2023-10-06T10:08:12.601Z CNTRLR Waiting for the controller to reconnect... 2023-10-06T10:08:14.102Z CNTRLR Re-opening serial port... 2023-10-06T10:08:15.106Z CNTRLR Waiting for the Serial API to start... 2023-10-06T10:08:15.544Z CNTRLR Serial API started 2023-10-06T10:08:15.545Z CNTRLR The controller is no longer unresponsive 2023-10-06 12:08:15.546 INFO Z-WAVE: Controller status: Controller is Ready
> 
> I run everything on a ODRIOD N2+ , I have disable soft reset and restarted the whole system (restart hardware)
> 
> Suddenly I noticed that Z-wave JS version 2.1.0 Is released with an "response time out support" feature :) After the upgrade I have no problems so far ....
> 
> ![image](https://user-images.githubusercontent.com/56930394/273175564-81a78b15-26dd-428f-b19c-f362f6d49384.png)

I can confirm that my problems are solved updating to 2.1.0

**Comment by bigmak40** [comment] 2023-10-06 14:51
@ashwin2101 your issue is different and should be a different ticket.

**Comment by firefighter4700** [comment] 2023-10-07 08:43
> > > Have anyone tried the 2.0.2 version? Are we back to normal with this? Had to uninstall my js ui addon and move all my z wave divices to the js addon. Really want to swich back again..
> > 
> > 
> > As I said in my above it seems to be working again with 2.02. I was having issues with it and it seems to be working again. You could try it and see if it works for you but its working for me.
> 
> Ok, wasnt sure if you had tested all yet, but good! I will try it out tomorrow and report back. Thaks!

I can confirm updating to Home Assistant 2023.10 gave me the option to download Z wave JS UI version 2.1.0 and all it working good for me again. Will absolutely start doing more backups and storing them longer in my case. Would still be nice to have the option for version rollback directly in the add ons tho in some cases..

**Comment by vectorxy** [comment] 2023-10-07 13:24
> > > > Have anyone tried the 2.0.2 version? Are we back to normal with this? Had to uninstall my js ui addon and move all my z wave divices to the js addon. Really want to swich back again..
> > > 
> > > 
> > > As I said in my above it seems to be working again with 2.02. I was having issues with it and it seems to be working again. You could try it and see if it works for you but its working for me.
> > 
> > 
> > Ok, wasnt sure if you had tested all yet, but good! I will try it out tomorrow and report back. Thaks!
> 
> I can confirm updating to Home Assistant 2023.10 gave me the option to download Z wave JS UI version 2.1.0 and all it working good for me again. Will absolutely start doing more backups and storing them longer in my case. Would still be nice to have the option for version rollback directly in the add ons tho in some cases..

Same experience here with my zwave issue. Thanks for the quick turn around fix for this.
